[platformio]
default_envs = build

[env]
framework = arduino
platform = atmelavr
board = uno
upload_speed = 115200
monitor_speed = 115200
monitor_filters = default
build_flags =
    -Wl,--relax ; This will optimize call to rcall, where possible.
extra_scripts = 
    pre:scripts/disasm.py
    pre:scripts/as_opts.py

[env:build]

[env:upload_and_monitor]
targets = upload, monitor
